### PR TITLE
[VFS-750] Fix backwards incompatibility in AbstractFileObject.getInputStream

### PR DESCRIPTION
**Pull request by boris-petrov**
A test for this should be written but this could happen later.

@garydgregory - please review, merge and release this as `2.5.1`.

### CODE REVIEW

**Comment by garydgregory** [comment]
Jira https://issues.apache.org/jira/browse/VFS-750

**Comment by garydgregory** [comment]
@boris-petrov 
i Fixed THIS in git master in a different manner. Please verify and close or comment in https://issues.apache.org/jira/browse/VFS-750. Also close this PR if THE fix works for you. TY Boris!

**Comment by boris-petrov** [comment]
@garydgregory - the fix in master seems fine. I'll be trying it in `2.5.1`. Would you mind releasing a hotfix release? Thanks!

**Comment by garydgregory** [comment]
@boris-petrov 
Make sure you try a SNAPSHOT build to confirm.

**Pull request closed without merging**
