### PR TITLE
VFS-841: copying Jackrabbit standalone Main class not to depend on wh…

### PR DESCRIPTION
**Pull request by woonsan**
…at's not supposed to be exposed by Jackrabbit2

### CODE REVIEW

**Comment by garydgregory** [comment]
@woonsan 
Thank you for the PR
Run 'mvn' before you push to catch these build failures.

**Comment by woonsan** [comment]
Hi @garydgregory ,

Yes, I think so. The Jackrabbit team believes that the Main class actually needs to be in standalone, not standalone-components and other projects such as commons-vfs2 need to just copy it. So they asked me to do this. ;-)

Kind regards,

Woonsan

**Comment by garydgregory** [comment]
Hi @woonsan 
Understood. All we need is for this PR not to break the build ;-) Would you please update this PR?

**Comment by garydgregory** [comment]
@woonsan 
Ping 😉

**Comment by woonsan** [comment]
@garydgregory , sorry for late. I will update this by the end of this week.

**Comment by garydgregory** [comment]
> @garydgregory , sorry for late. I will update this by the end of this week.

TY!

**Pull request merged**
