### PR TITLE
WIP: Simplify UriParser

### PR DESCRIPTION
**Pull request by raboof**
(not for review yet, intermediate PR to test on CI)

### CODE REVIEW

**Comment by garydgregory** [comment]
Maybe one the SSH tests is hung:
```
[INFO] Running org.apache.commons.vfs2.provider.sftp.SftpPutChannelTestCase
Exception in thread "pool-34-thread-1" java.lang.AssertionError
	at org.apache.sshd.common.session.AbstractSession.decode(AbstractSession.java:519)
	at org.apache.sshd.common.session.AbstractSession.messageReceived(AbstractSession.java:236)
	at org.apache.sshd.common.AbstractSessionIoHandler.messageReceived(AbstractSessionIoHandler.java:58)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:1015)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:650)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.access$1300(DefaultIoFilterChain.java:49)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain$EntryImpl$1.messageReceived(DefaultIoFilterChain.java:1128)
	at org.apache.mina.core.filterchain.IoFilterAdapter.messageReceived(IoFilterAdapter.java:122)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.callNextMessageReceived(DefaultIoFilterChain.java:650)
	at org.apache.mina.core.filterchain.DefaultIoFilterChain.fireMessageReceived(DefaultIoFilterChain.java:643)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(AbstractPollingIoProcessor.java:539)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$1200(AbstractPollingIoProcessor.java:68)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.process(AbstractPollingIoProcessor.java:1224)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.process(AbstractPollingIoProcessor.java:1213)
	at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:683)
	at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```
We are on an antique version of Mina, which I've tried to update in the past, but didn't manage to get working...

**Comment by raboof** [comment]
retriggered by force-pushing

**Comment by garydgregory** [comment]
FYI @raboof All tests passed.

**Comment by japplis** [comment]
I think this PR would also remove the need to merge https://github.com/apache/commons-vfs/pull/547

**Comment by raboof** [comment]
closing in favor of #558

**Pull request closed without merging**
