### PR TITLE
try to upgrade sshd to 2.8.0

### PR DESCRIPTION
**Pull request by XenoAmess**

### CODE REVIEW

**Comment by garydgregory** [comment]
Hi @XenoAmess 
Did the tests pass for you locally before you created the PR? I wonder what is different about your set up.

**Comment by XenoAmess** [comment]
> Hi @XenoAmess Did the tests pass for you locally before you created the PR? I wonder what is different about your set up.

@garydgregory 

SftpProviderStreamProxyModeTestCase will run forever and seems would never stop.

Then in SftpProviderClosedExecChannelTestCase , 
```
PermissionsTests.testExecutable
PermissionsTests.testWriteable
PermissionsTests.testReadable
```
these 3 tests fails.

other tests looks well on local.

win10, jdk javac 1.8.0_275

Seems I still didn't totally understand the HACK you applied to sshd in original AbstractSftpProviderTestCase.

Hope this can help others when they try this, but maybe I should give up.

**Comment by garydgregory** [comment]
Hi @XenoAmess 
Don't get discouraged. I asked for help on the mailing list because updating 'sshd' and 'ftp-core' seem like non-trivial efforts based on my past experiences. If it had been trivial, I would have done it. In fact, I've already done work like you have in this very PR a long time ago, but did not take the time to figure out the bugs, and so, I moved on to other more pressing issues. Getting the code to compile is trivial compared to getting the tests to pass. Some tasks take a few hours, other days, and sometimes weeks.
Good luck, whatever path you chose to take.

**Comment by XenoAmess** [comment]
> Hi @XenoAmess Don't get discouraged. I asked for help on the mailing list because updating 'sshd' and 'ftp-core' seem like non-trivial efforts based on my past experiences. If it had been trivial, I would have done it. In fact, I've already done work like you have in this very PR a long time ago, but did not take the time to figure out the bugs, and so, I moved on to other more pressing issues. Getting the code to compile is trivial compared to getting the tests to pass. Some tasks take a few hours, other days, and sometimes weeks. Good luck, whatever path you chose to take.

(sigh)
this is out of my ability...
pr closed.

**Comment by garydgregory** [comment]
@XenoAmess 
An alternative would be to migrate to a lesser version, just to get is out of the 0.x version range.

**Pull request closed without merging**
