### PR TITLE
VFS-782 - Pass correct proxy authentication credentials

### PR DESCRIPTION
**Pull request by satish-csi**
VFS-782 - pass correct proxy authentication credentials mainly proxyAuthData instead of authData

### CODE REVIEW

**Review by michael-o — APPROVED** [review]

**Comment by garydgregory** [comment]
@satish-csi Needs unit tests.

**Comment by satish-csi** [comment]
@garydgregory I have added test case for proxy authentication

**Comment by garydgregory** [comment]
Hi @satish-csi 
You need better tests.
The tests don't show that anything was fixed because they succeed when run without the changes to `src/main`.
I expect:
- Apply patch to `src/test` only
- New tests fail
- Apply remainder of the patch to `src/main`
- All tests pass

**Comment by garydgregory** [comment]
I pushed the tests portion of this PR to git master since they do test the code, but not the main change.

**Comment by garydgregory** [comment]
Is still PR still valid since #120 has been merged? If so, please rebase on master and re-validate.

**Comment by satish-csi** [comment]
This PR is still valid, since we are setting authdata instead of proxyauth data
image

**Comment by garydgregory** [comment]
> This PR is still valid, since we are setting authdata instead of proxyauth data, it is for both htt5fileprovider and http4fileprovider
> image

I should have asked you to rebase on master and see if that case is now handled. May you please check?

**Comment by satish-csi** [comment]
Hi @garydgregory 
I had look at master files
```
https://github.com/apache/commons-vfs/blob/master/commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/http5/Http5FileProvider.java
https://github.com/apache/commons-vfs/blob/master/commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/http4/Http4FileProvider.java
```
These doesnt have this PR changes

**Comment by garydgregory** [comment]
> Hi @garydgregory
> I had look at master files
> 
> ```
> https://github.com/apache/commons-vfs/blob/master/commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/http5/Http5FileProvider.java
> https://github.com/apache/commons-vfs/blob/master/commons-vfs2/src/main/java/org/apache/commons/vfs2/provider/http4/Http4FileProvider.java
> ```
> 
> These doesnt have this PR changes

May you please rebase on master then.

**Comment by satish-csi** [comment]
Hi @garydgregory ,
I have rebased PR, resolved conflict,
If I pass some dummy proxy URI http://test:test@squid-test.com:3128, without my PR changes
then it fails with error **java.lang.IllegalArgumentException: Username may not be null**
and PR fixes issue

**Comment by garydgregory** [comment]
> Hi @garydgregory ,
> I have rebased PR, resolved conflict,
> If I pass some dummy proxy URI http://test:test@squid-test.com:3128, without my PR changes
> then it fails with error **java.lang.IllegalArgumentException: Username may not be null**
> and PR fixes issue

What is squid-test?

**Comment by satish-csi** [comment]
> > Hi @garydgregory ,
> > I have rebased PR, resolved conflict,
> > If I pass some dummy proxy URI http://test:test@squid-test.com:3128, without my PR changes
> > then it fails with error **java.lang.IllegalArgumentException: Username may not be null**
> > and PR fixes issue
> 
> What is squid-test?

It's just dummy uri to which I tried

**Pull request merged**
