### PR TITLE
Use parent group ids for all artifacts

### PR DESCRIPTION
**Pull request by abashev**
Hi, I'm the main contributor for this project https://github.com/abashev/vfs-s3 I have a lot of complaints about our 'custom' build for commons-vfs project so I've decided to submit everything that I have to common repo.
There is my first one - using parent group ids for all artifacts. I have to prepare own builds for commons-vfs so for me it is hard to track a lot of places with my group id. With this commit, I will be able to change only parent group id and leave everything as is.

### CODE REVIEW

**Comment by ecki** [comment]
I am not a big fan of it as you cannot easily work on the core module but I also won’t oppose it. Could you squash your commits.

**Comment by abashev** [comment]
@ecki done

**Comment by abashev** [comment]
I did rebase for latest master

**Comment by boris-petrov** [comment]
@garydgregory, @ecki - could you take a look/merge this so @abashev can continue with his PRs? :)

**Pull request closed without merging**
