### PR TITLE
Minors improvements

### PR DESCRIPTION
**Pull request by arturobernalg**
* Remove Unused import
* Simplifiable assertion
* Simplify conditions
* Make method void.

### CODE REVIEW

**Comment by garydgregory** [comment]
Don't change the internal APIs for now please.

**Comment by arturobernalg** [comment]
> Don't change the internal APIs for now please.

HI @garydgregory 
What you mean? 
TY

**Comment by garydgregory** [comment]
> > Don't change the internal APIs for now please.
> 
> HI @garydgregory
> What you mean?
> TY

Don't change method signatures, sorry I was not more precise in my comment.

**Comment by arturobernalg** [comment]
> > > Don't change the internal APIs for now please.
> > 
> > 
> > HI @garydgregory
> > What you mean?
> > TY
> 
> Don't change method signatures, sorry I was not more precise in my comment.

Hi @garydgregory 
Reverted the change of signature.
TY

**Pull request closed without merging**
