### PR TITLE
SFTP HTTP and SOCKS proxy authentication

### PR DESCRIPTION
**Pull request by rayzzed**
Proxy user and password are now transmitted to the HTTP or SOCKS proxy.

### CODE REVIEW

**Comment by rayzzed** [comment]
One Test fails on GetContentInfoFunctionalTest.testGetContentInfo() because of "java.lang.IllegalStateException: Connection factory has been shutdown." in org.apache.commons.httpclient.MultiThreadedHttpConnectionManager.doGetConnection...
Doesn't seem to be related to this commit.

**Comment by mkovacek** [comment]
When is planned to include this? Proxy auth is urgently needed!

**Comment by mkovacek** [comment]
When is planned next release?

**Comment by garydgregory** [comment]
No plans ATM but you can build or download a snapshot.

**Comment by mkovacek** [comment]
Hmm can you help me with that? Not sure how to build and deploy snapshot version

**Comment by garydgregory** [comment]
Only an Apache Commons PMC member can deploy to the Apache Snapshot repository. What you can do though is build the jar with `mvn package`.

**Comment by garydgregory** [comment]
Also, I am considering creating a release candidate this week. So please test as much as you can and provide more PRs if needed.

**Comment by mkovacek** [comment]
Sounds great, I would really appreciate if you can build snapshots version :) Having troubles with local building

**Comment by garydgregory** [comment]
I just deployed 2.4-SNAPSHOT.

**Comment by boris-petrov** [comment]
@garydgregory - these snapshots you're not uploading to Maven central, correct? Why not? And where do you put them?

**Comment by garydgregory** [comment]
Because snapshots are not official releases. Snapshots are here: https://repository.apache.org/snapshots/

**Comment by boris-petrov** [comment]
@garydgregory - thanks! Just a note - these don't seem to be snapshots at least according to what Gradle thinks. This:

```gradle
	maven {
		url 'https://repository.apache.org/snapshots'
		content {
			includeGroup 'org.apache.commons'
			snapshotsOnly()
		}
	}
```

Doesn't work - that is, Gradle then doesn't find `org.apache.commons:commons-vfs2:2.4-20190325.151337-1`. However, if I remove `snapshotsOnly`, it works. Not sure why, if you think this is important, you can try it out. I guess it's because of the filename - probably it expects `-SNAPSHOT` which you don't seem to have in your file names.

**Comment by garydgregory** [comment]
@boris-petrov:
The version you specify must be `2.4-SNAPSHOT`, not `2.4`, but I don't even see a version number in your snippet.

**Comment by boris-petrov** [comment]
@garydgregory - you are right, I did some mistake the first time. All works fine, sorry for the confusion.

**Pull request closed without merging**
