### PR TITLE
VFS-784 - Pass SSL connection factory to PoolingHttpClientConnectionManager

### PR DESCRIPTION
**Pull request by satish-csi**
Pass SSLConnectionSocketFactory to PoolingHttpClientConnectionManager as its failing with nginx with squid proxy

### CODE REVIEW

**Review by michael-o — COMMENTED** [review]
This does not correspond to the issue description. Your problem is that your do not trust this certificate. It is that plain simple.

**Comment by satish-csi** [comment]
@michael-o I do pass valid certificate in keystore! it doesn't work until I pass SSL socket factory to PoolingHttpClientConnectionManager

**Comment by michael-o** [comment]
> 
> 
> @michael-o I do pass valid certificate in keystore! it doesn't work until I pass SSL socket factory to PoolingHttpClientConnectionManager

I was refering to the default trust store of Java (`cacerts`).

**Comment by satish-csi** [comment]
> > @michael-o I do pass valid certificate in keystore! it doesn't work until I pass SSL socket factory to PoolingHttpClientConnectionManager
> 
> I was refering to the default trust store of Java (`cacerts`).

Actually I was trying with our wan custom keystore passed via Http4FileSystemConfigBuilder

**Comment by garydgregory** [comment]
@satish-csi Needs unit tests.

**Comment by garydgregory** [comment]
Can this be closed?

**Comment by xiamubobby** [comment]
Please don't close this without merging it as it looks like a confirmed issue: https://stackoverflow.com/questions/19517538/ignoring-ssl-certificate-in-apache-httpclient-4-3 as it is embedded inside HttpClient.

**Comment by satish-csi** [comment]
@garydgregory This needs to be merged into master! This issue can be reproduced but requires infra for writing testcases hence I am unable to write test cases.

**Comment by garydgregory** [comment]
> @garydgregory This needs to be merged into master! This issue can be reproduced but requires infra for writing testcases hence I am unable to write test cases.

@satish-csi 
As we are volunteer-based organization, may I suggest that you would be better served in more diplomatic engagement with the community instead of issuing commands like "This needs to be merged into master!"

If you want any PR to get more attention, providing tests is the way to go. We have a lot of existing tests you are free to use as inspiration, specifically in the HTTP provider packages:

- org.apache.commons.vfs2.provider.http
- org.apache.commons.vfs2.provider.http4
- org.apache.commons.vfs2.provider.http4s
- org.apache.commons.vfs2.provider.http5
- org.apache.commons.vfs2.provider.http5s
- org.apache.commons.vfs2.provider.https

**Comment by satish-csi** [comment]
> > @garydgregory This needs to be merged into master! This issue can be reproduced but requires infra for writing testcases hence I am unable to write test cases.
> 
> @satish-csi
> As we are volunteer-based organization, may I suggest that you would be better served in more diplomatic engagement with the community instead of issuing commands like "This needs to be merged into master!"
> 
> If you want any PR to get more attention, providing tests is the way to go. We have a lot of existing tests you are free to use as inspiration, specifically in the HTTP provider packages:
> 
> * org.apache.commons.vfs2.provider.http
> * org.apache.commons.vfs2.provider.http4
> * org.apache.commons.vfs2.provider.http4s
> * org.apache.commons.vfs2.provider.http5
> * org.apache.commons.vfs2.provider.http5s
> * org.apache.commons.vfs2.provider.https

Hi @garydgregory 
I am extremely sorry for making incorrect statement, I was expecting little hint on how to write testcase for infrastructure dependencies, but no worries will dig more into code, 
I apologise for inconvenience!

**Comment by garydgregory** [comment]
Hi @satish-csi 
I feel I must apologize as well as for what seems in retrospect like an overaction on my part. Do look at out existing tests indeed. I believe you should find what you need to write your own tests. And this is not an inconvenience, only side-effects of communicating over an imperfect medium :-)
Looking forward to your further contribution,
Gary

**Pull request merged**
