### PR TITLE
VFS-686: webdav4 provider based on the latest Jackrabbit 2.x

### PR DESCRIPTION
**Pull request by woonsan**
**NOTE**: Not ready for merge yet; just for review purpose for now because of Jackrabbit snapshot dependency for JCR-4401. So, once new Jackrabbit release is cut, I'll ask for reviews and merged on this pull request in the mailnglist.

Anyway, so far what I did:
- Add new submodule, commons-vfs-jackrabbit3, which implements `webdav4`, based on `http4` provider.
- All the unit tests work fine now, depending on Jackrabbit 2.19.2-SNAPSHOT at the moment.

TODOs:
- Java 9 JPMS rules
- Move the old, `webdav` provider to a new module, commons-vfs2-jackrabbit2.
- Add `webdav4s` provider based on `http4s`.

### CODE REVIEW

**Comment by woonsan** [comment]
> I see a merge from trunk but that branch should not exist. Please master.

Thank you so much @garydgregory ! I've just reverted. You saved me!

**Comment by garydgregory** [comment]
What happens in a local build for you? Do see failures like https://travis-ci.org/apache/commons-vfs/builds/514209996?utm_source=github_status&utm_medium=notification

**Comment by garydgregory** [comment]
Travis says at https://api.travis-ci.org/v3/job/514209997/log.txt says:
```
Failed tests: 
  VfsClassLoaderTests>AbstractProviderTestCase.runTest:198->testGetResourcesNoLayerLocal:161 subdir4.jar/ is required for testing file:///home/travis/build/apache/commons-vfs/commons-vfs2-jackrabbit2/target/test-classes/test-data/read-tests/dir1/subdir4.jar
  ContentTests>AbstractProviderTestCase.runTest:198->testAllContent:39->assertSameContent:53->assertSameContent:49 webdav://admin@localhost:42383/repository/default/read-tests/dir1/subdir4.jar
  ProviderReadTests>AbstractProviderTestCase.runTest:198->testDotJarFolderName:329
  ProviderReadTests>AbstractProviderTestCase.runTest:198->testDotJarFolderNameLayer:339 subdir4.jar/ must exist as folder, check test setup.
  ProviderReadTests>AbstractProviderTestCase.runTest:198->testFindFiles:311 expected:<0> but was:<1>
  ProviderReadTests>AbstractProviderTestCase.runTest:198->testSort:165 expected:<0> but was:<1>
  ProviderReadTests>AbstractProviderTestCase.runTest:198->testStructure:64->assertSameStructure:105 count children of "webdav://admin@localhost:42383/repository/default/read-tests/dir1" expected:<7> but was:<6>

Tests run: 84, Failures: 7, Errors: 0, Skipped: 0
```

**Comment by woonsan** [comment]
@garydgregory , when I merged master locally, it started failing like that...
Some test env setting might have changed bc26e4b1c0a11b8609cab880b1821d3560f34d06 to 0a1f3f6f38517d5819cda5e6aac33364f39c407c. Will look into it tonight..

**Comment by garydgregory** [comment]
Hi @woonsan ,
To be clear, the tests are still failing :-(
Gary

**Comment by woonsan** [comment]
@garydgregory , just fyi, I'm trying to figure out how to reproduce this locally. Strangely, my local tests were successful... :(

> junit.framework.AssertionFailedError: webdav://admin@localhost:36382/repository/default/read-tests/dir1/subdir4.jar
> ...

**Comment by woonsan** [comment]
Hi @garydgregory , I think I found the cause. It's all my bad. For some reason -- probably due to my git env setting, some resource files were not committed/pushed. e.g, commons-vfs2-jackrabbit2/src/test/resources/test-data/read-tests/subdir4.jar and its descendants, commons-vfs2-jackrabbit2/src/test/resources/test-data/*.gz, *.jar, *.tar, ...
Sorry and thanks for noticing this problem! I'll fix it asap.

**Comment by garydgregory** [comment]
Hi @woonsan,

What is the status of this PR? Is it still "Not ready for merge"?

Gary

**Comment by woonsan** [comment]
Hi @garydgregory ,
Yet not ready status because jackrabbit3 submodule depends on the following (in root pom):
> <jackrabbit3.version>2.19.2-SNAPSHOT</jackrabbit3.version>
I need to get the release out soon but will take some time.

Woonsan

**Comment by woonsan** [comment]
Hi @garydgregory , I figured out how to make this PR reviewable and mergeable right now:
- JCR-4401 is really about simple dependency provision for unit testing in the end.
- Therefore, if I add dependencies expanding what I did for JCR-4401 in jackrabbit3 submodule with a custom Main class like what's done for old webdav test case, then this will work, with downgrading the JR dependency to 2.18.0.
- I can create a separate JIRA ticket to simplify the test case taking advantage of JCR-4401 later.

I'll wrap it up and ask again for reviews soon.

**Comment by woonsan** [comment]
Hi @garydgregory ,

This PR is now ready to review!

This PR includes (a) new `webdav4` provider based on the latest stable Jackrabbit release, **2.18.0** in a separate jar submodule: `commons-vfs2-jackrabbit3`, (b) the old `webdav3` provider based on Jackrabbit 1.x moved to a separate JAR module: `commons-vfs2-jackrabbit2`.
Java 9 JPMS and webdav4s (on https) are not included. Those can be done with new tickets.

Please note that `commons-vfs2-jackrabbit3` submodule skips both test-compile and tests totally by default because it depends on Jackrabbit 2.19.2-SNAPSHOT at the moment for testing. Ref: JCR-4401.
Its testing can be enabled with `mvn clean install -DtestJackrabbit3`, which works fine on env with the snapshot dependency access.
Once Jackrabbit 2.19.2 or higher becomes available, we can probably enable the tests by default later.
Is this okay?

Thanks in advance!

Kind regards,

Woonsan

**Comment by garydgregory** [comment]
Travis says green on Java 8 :-) Now we wait on JR...

**Comment by woonsan** [comment]
Now it's really ready to review. It now depends on the latest JR release: 2.19.2. Thanks!

**Comment by garydgregory** [comment]
Hi @woonsan 

Please refresh my memory if you've already explained this before:

in pom.xml I see:

```
    <jackrabbit2.version>1.6.5</jackrabbit2.version>
    <jackrabbit3.version>2.19.2</jackrabbit3.version>
```

and in a module:

```
  <artifactId>commons-vfs2-jackrabbit2</artifactId>
  <description>Apache Commons VFS is a Virtual File System library - Jackrabbit2-based WebDAV provider.</description>
...
    <dependency>
      <groupId>org.apache.jackrabbit</groupId>
      <artifactId>jackrabbit-webdav</artifactId>
      <version>${jackrabbit2.version}</version>
    </dependency>
```

Why are we calling JR1 support "2" and JR2 support "3"?

It's a bit confusing.

Thoughts?

Gary

**Comment by woonsan** [comment]
Hi @garydgregory ,

Yes, the naming is tricky here. The main reason I mentioned is that Jackrabbit2 had upgraded its HttpClient from v3 to v4 since v2.16. [1] Therefore, it is actually okay to use any Jackrabbit 2.x version before 2.16 with the old commons-vfs webdav provider.

As of JR 2.16, it started using HC 4.x, which actually started introducing backward incompatibility -- e.g, some HC interfaces/classes have been used in JR webdav API as well, and those had to be changed breaking the compatibility.

Therefore, even if commons-vfs's dependency on JR was set to 1.x, it works fine with pre-JR 2.16 versions; as a result, JR itself in v2.14 has a dependency on commons-vfs2 for WebDAV-based DataStore as well, and it works totally fine. In other words, JR-based CMS systems use commons-vfs2 webdav with JR 2.14 now.

So, I justified using the old one as jackrabbit2 and the new one as jackrabbit3 [3] by mentioning that the Jackrabbit3 ("OAK") is still using the Jackrabbit API in v2.16+. In other words, Jackrabbit API is also used for "Jackrabbit3" nowadays, and JR itself won't be released in v3 at all since OAK is to replace it as "Jackrabbit 3".

Yeah, weird, just figured out a justification. ;-)

Regards,

Woonsan

[1] https://lists.apache.org/thread.html/71dc8ab6526b114fc16f60727ea66ee4c9c4e02dbc10794b5a9477e2@%3Cdev.commons.apache.org%3E
[2] https://lists.apache.org/thread.html/2632179eab395e25261f8e55bfebd9d6da9bb72b769a0b56c5b6bfd8@%3Cdev.commons.apache.org%3E

**Comment by woonsan** [comment]
BTW, I'm open to any better name suggestions. On top off my head, "commons-vfs2-jackrabbit2-hc3" (with updating the version from 1.6.5 to 2.14.x) vs "commons-vfs2-jackrabbit2-hc4" (with 2.19.2) could be too verbose?

**Comment by garydgregory** [comment]
Hi @woonsan,

So sorry I got side tracked. May you please rebase on master so we can get a fresh set of Travis CI builds.

Gary

**Comment by woonsan** [comment]
Hi @garydgregory ,
I've just merged mater. It's great to see greens even for JVM11! Great work!
Woonsan

**Comment by garydgregory** [comment]
@woonsan Thank you.

WRT the patch. could there might still be conflicts:
```
C:\git\commons-vfs>git apply \temp\52.patch.txt
/temp/52.patch.txt:1685: trailing whitespace.
/*
/temp/52.patch.txt:1686: trailing whitespace.
 * Licensed to the Apache Software Foundation (ASF) under one or more
/temp/52.patch.txt:1687: trailing whitespace.
 * contributor license agreements.  See the NOTICE file distributed with
/temp/52.patch.txt:1688: trailing whitespace.
 * this work for additional information regarding copyright ownership.
/temp/52.patch.txt:1689: trailing whitespace.
 * The ASF licenses this file to You under the Apache License, Version 2.0
error: patch failed: pom.xml:179
error: pom.xml: patch does not apply
error: patch failed: pom.xml:554
error: pom.xml: patch does not apply
error: patch failed: pom.xml:36
error: pom.xml: patch does not apply
error: patch failed: pom.xml:194
error: pom.xml: patch does not apply
error: patch failed: pom.xml:194
error: pom.xml: patch does not apply
error: patch failed: pom.xml:194
error: pom.xml: patch does not apply
```

Can you try to apply the patch locally to your master to see what happens? 

I wanted to review it in Eclipse instead of here...

Thank you!

**Comment by woonsan** [comment]
Hi @garydgregory ,
I don't know, but the patch file downloaded from GitHub seems to make problems.
I found an alternative by creating and uploading the patch file to the JIRA ticket: https://issues.apache.org/jira/browse/VFS-686. Could you try with that alternative instead?
Thanks,
Woonsan

**Comment by woonsan** [comment]
On second thought, it seems better to rename "commons-vfs2-jackrabbit2" to "commons-vfs2-jackrabbit", and "commons-vfs2-jackrabbit3" to "commons-vfs2-jackrabbit2" because the former depends on Jackrabbit 1.5.x and the latter on Jackrabbit 2.19.x.
I will rename those later this week unless there are better ones.

**Comment by garydgregory** [comment]
Sounds good.

**Comment by garydgregory** [comment]
Hi @woonsan 
Thank you for the update, I think the hopefully last item to take care of is to update new `@since` tags to `2.5.0`.

**Comment by garydgregory** [comment]
Is there a version of JR 1.x that would avoid:
```
Running org.apache.commons.vfs2.provider.webdav.test.WebdavProviderTestCase
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/travis/.m2/repository/org/slf4j/slf4j-log4j12/1.5.11/slf4j-log4j12-1.5.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/travis/.m2/repository/org/apache/jackrabbit/jackrabbit-standalone/1.6.5/jackrabbit-standalone-1.6.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
2019-10-17 09:08:58,002 [main] ERROR unavailable
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at org.apache.jasper.compiler.JspRuntimeContext.<init>(JspRuntimeContext.java:174)
	at org.apache.jasper.servlet.JspServlet.init(JspServlet.java:150)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:431)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:643)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1234)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:517)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:460)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.handler.RequestLogHandler.doStart(RequestLogHandler.java:115)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:222)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.apache.commons.vfs2.provider.webdav.test.JackrabbitMain.run(JackrabbitMain.java:232)
	at org.apache.commons.vfs2.provider.webdav.test.WebdavProviderTestCase.startJackrabbit(WebdavProviderTestCase.java:237)
	at org.apache.commons.vfs2.provider.webdav.test.WebdavProviderTestCase.setUpClass(WebdavProviderTestCase.java:216)
	at org.apache.commons.vfs2.provider.webdav.test.WebdavProviderTestCase.access$100(WebdavProviderTestCase.java:55)
	at org.apache.commons.vfs2.provider.webdav.test.WebdavProviderTestCase$1.setUp(WebdavProviderTestCase.java:245)
	at org.apache.commons.vfs2.test.AbstractTestSuite.lambda$run$0(AbstractTestSuite.java:129)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at org.apache.commons.vfs2.test.AbstractTestSuite.run(AbstractTestSuite.java:134)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
VfsClassLoaderTests no layered .jar provider, skipping.
created threads still running:
#2: main	MultiThreadedHttpConnectionManager cleanup	WAITING	daemon	null
```
See https://travis-ci.org/apache/commons-vfs/jobs/599058150

**Comment by woonsan** [comment]
@garydgregory , after confirming local build with oracle-jdk11 working fine, I kicked in travis again and it seems to build fine now.

Regarding the java.lang.ClassCastException from jetty (v6.x), unfortunately JR 1.6.5 is the latest release in 1.x range. However, it seems like not affecting the test running itself; it seems to throw an exception only when initializing JSP engine which is never used in JR webdav server.
FYI, JR2.x uses jetty 9.x.

**Pull request merged**
