### PR TITLE
refactor CountingListener to improve test design

### PR DESCRIPTION
**Pull request by wx930910**
Fixes [VFS-809](https://issues.apache.org/jira/browse/VFS-809)

### Description
Replace test class [CountingListener](https://github.com/apache/commons-lang/blob/69c9593cc1da760bb4dbcf32f4ae755c54376b77/src/test/java/org/apache/commons/lang3/concurrent/AtomicSafeInitializerTest.java#L67) by mocking object created by Mockito.

<hr>

##### Key changed/added classes in this PR
- Create mocking object to replace test subclass `CountingListener`, decouple test from production code.
- Extract AtomicLong variables out of the test subclass. Use the extracted variables in assertation statement to check methods invocation status and make test condition more explict.

<hr>

### CODE REVIEW

**Comment by garydgregory** [comment]
This PR looks quite complex compared to the exting code. Why make maintenance more of a burden going forward?  What am I missing here?

**Comment by wx930910** [comment]
> This PR looks quite complex compared to the exting code. Why make maintenance more of a burden going forward? What am I missing here?

@garydgregory Thanks for replying, actually we can get rid of all overridden methods as well as the attributes for tracking the overridden method exectuion by using Mockito. We can directly verify the method execution time by using `Mockito.verify()`, do you think the logic and maintenance will be better if we do it in that way?

**Comment by wx930910** [comment]
@garydgregory Changed the code accordingly, no longer required AtomicLong variables and overridden methods, we just need to change the assertion to `Mockito.verify()`.

**Comment by wx930910** [comment]
@garydgregory Thanks for your feedback and I changed code logic, do you think the updated code is less complex compared to the existing code? (Given the fact that we no longer need the test child class and all overridden methods)

**Comment by garydgregory** [comment]
Same comments as I wrote in the other PR RE Mockito.

**Comment by garydgregory** [comment]
Closing, no more feedback.

**Pull request closed without merging**
