### PR TITLE
[VFS-497] Ported filters from Commons IO

### PR DESCRIPTION
**Pull request by michael-schnell**
https://issues.apache.org/jira/browse/VFS-497

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
@ecki @garydgregory Any opinion on this?

**Comment by garydgregory** [comment]
I do not like it. Commons CVS is already a kitchen sink of sorts, so would just centralize all filters in Commons IO and make VFS depend on IO.

**Comment by garydgregory** [comment]
Darn autocomplete! I meant VFS, not CSV.

**Comment by michael-schnell** [comment]
I checked this option before I decided to port the code to VFS. Unfortunately commons IO filter uses the Java type File all over the place. You would need to make an incompatible change to the commons io code or create a new package for it. So, I'd suggest just to merge the (three years old) code.

**Comment by ecki** [comment]
It's a bit heavyweight and I had no need for those filters however I like the fact that the patch does not add a dependency, so it is fine with me. Will merge it.

**Comment by michael-schnell** [comment]
Great. Go ahead!

**Comment by garydgregory** [comment]
Merged with some changes.

**Pull request closed without merging**
