### PR TITLE
(doc) add project diagram links to README.md

### PR DESCRIPTION
**Pull request by alexkarezin**
Adding a link to the high-level diagrams including module, library dependency and others (https://sourcespy.com/github/apachecommonsvfs/). Built directly from source and updated on schedule. Intended to simplify developer's introduction to the project.

In the spirit of transparency - I am the author of the diagrams. Hope contributors find it useful.

### CODE REVIEW

**Comment by alexkarezin** [comment]
Gary, any chance you can review the request? This is a documentation-only change, happy to make any adjustments needed. Thank you! @garydgregory

**Comment by garydgregory** [comment]
-1: Not as this PR stands.

These pages should be, IMO, generated as part the Maven site generation, preferably from a Maven plugin, just like Javadoc. Then each time you change the source, you  build and see how the graphics change. I've considered generating UML documents in the past, but I've not seen anyone ask for it IIRC.

Another advantage of this approach is that you get a self contained site when you create a release candidate and its site. Everything is tied together. 

I don't see any copyright or license on the page. Is the site generated as Apache License 2.0? Creative Commons?

**Comment by alexkarezin** [comment]
Thank you Gary! I my thought was that limited reference (a badge and one link) would bring a sufficient benefit without disturbing existing documentation structure and the build process.

The diagrams are built and hosted on a third-party site very similar to how other code analysis tools work (including javadoc, codecov, etc). I humbly assumed that following the pattern would be appropriate.

Changes to the source code are picked up automatically from GitHub.

I will grant and display Apache 2.0 license on all the pages as requested.

Let me know if you think removal of the link in the content and leaving the badge in the header (along with javadoc, codecov, etc) would be more appropriate.

Again, huge thank you for your attention and time.

**Comment by garydgregory** [comment]
Closing as discussed

**Pull request closed without merging**
